// <auto-generated />
using System;
using LiveLifeCoffee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiveLifeCoffee.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiveLifeCoffee.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("LiveLifeCoffee.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("LiveLifeCoffee.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("LiveLifeCoffee.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Sıcak İçecekler",
                            Description = "Taze çekilmiş, yumuşak ve aromatik filtre kahve.",
                            IsAvailable = true,
                            Name = "Filtre Kahve",
                            Price = 65.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sıcak İçecekler",
                            Description = "Yoğun ve güçlü İtalyan usulü espresso.",
                            IsAvailable = true,
                            Name = "Espresso",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sıcak İçecekler",
                            Description = "Sıcak suyla seyreltilmiş, yumuşak içimli espresso.",
                            IsAvailable = true,
                            Name = "Americano",
                            Price = 70.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sıcak İçecekler",
                            Description = "Bol sıcak süt ve hafif süt köpüğü ile espresso.",
                            IsAvailable = true,
                            Name = "Latte",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sıcak İçecekler",
                            Description = "Eşit oranda espresso, sıcak süt ve yoğun süt köpüğü.",
                            IsAvailable = true,
                            Name = "Cappuccino",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sıcak İçecekler",
                            Description = "Çikolata şurubu, espresso, sıcak süt ve krema.",
                            IsAvailable = true,
                            Name = "Mocha",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Soğuk İçecekler",
                            Description = "Buz üzerine soğuk süt ve espresso.",
                            IsAvailable = true,
                            Name = "Iced Latte",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Soğuk İçecekler",
                            Description = "Buz ve soğuk su ile hazırlanmış ferahlatıcı espresso.",
                            IsAvailable = true,
                            Name = "Iced Americano",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Soğuk İçecekler",
                            Description = "12 saat soğuk suda demlenmiş pürüzsüz kahve.",
                            IsAvailable = true,
                            Name = "Cold Brew",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Soğuk İçecekler",
                            Description = "Buzla karıştırılmış, kremalı soğuk kahve tatlısı.",
                            IsAvailable = true,
                            Name = "Frappuccino",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Soğuk İçecekler",
                            Description = "Taze sıkılmış limon ve nane yaprakları ile.",
                            IsAvailable = true,
                            Name = "Limonata",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Atıştırmalıklar",
                            Description = "İçi akışkan, üstü yanık enfes İspanyol keki.",
                            IsAvailable = true,
                            Name = "San Sebastian Cheesecake",
                            Price = 140.00m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Atıştırmalıklar",
                            Description = "Yoğun çikolatalı, fıstık parçalı ıslak kek.",
                            IsAvailable = true,
                            Name = "Brownie",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Atıştırmalıklar",
                            Description = "Tam buğday ekmeği üzerine taze avokado, limon ve kırmızı biber.",
                            IsAvailable = true,
                            Name = "Avokado Toast",
                            Price = 90.00m
                        });
                });

            modelBuilder.Entity("LiveLifeCoffee.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LiveLifeCoffee.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LiveLifeCoffee.Models.CartItem", b =>
                {
                    b.HasOne("LiveLifeCoffee.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiveLifeCoffee.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
